### ISSUE TITLE
Error While deploying cloudformation template

### ISSUE THREAD

**Issue by PreetamAWS** [aws-samples/ac-multi-region-apis#1]
Hi Team 

We are deploying the below blog for \"Build a multi-region resilient contact center with Amazon Connect global resiliency\"
https://aws.amazon.com/blogs/contact-center/build-a-multi-region-resilient-contact-center-with-amazon-connect-global-resiliency/

We are facing the below error.
Properties validation failed for resource webSiteCreator with message: #/Code: expected type: JSONObject, found: String.

**Comment by ramprasadsv** [comment]
@PreetamAWS Can you please try now, we fixed the link that was broken in the blog.

**Comment by rahjos4** [comment]
@ramprasadsv 
Re-tried the same in Oregon(US-West) & getting S3 access denied error. Please refer attachment.

![oregon_template_error](https://user-images.githubusercontent.com/98079119/209168336-5e13e317-4ce0-4f56-b1af-436710f2dea1.JPG)

**Comment by Kannan2022** [comment]
@PreetamAWS mee too facing same issue,

**Comment by ramprasadsv** [comment]
@Kannan2022 @PreetamAWS @rahjos4 Please try now, we had a typo in the folder name that was corrected.  I ran the CFT in my account and it went thru without any issues.
