### ISSUE TITLE
\"#/Code: expected type: JSONObject, found: String

### ISSUE THREAD

**Issue by Tarunjain19** [aws-samples/ac-multi-region-apis#2]
Hi Team,

We are getting the error while run the cloud formation template . We have open the ticket with support team and they have suggest some issue with cloud formation template Please check with blog owner.

The Issue:
========
I do understand that while trying to impelment the solution in Link: [1] below, the CloudFormation stack failed with error message: \"#/Code: expected type: JSONObject, found: String\".

Investigation:
===========
Checking the CloudFormation stack events and the related CloudTrail background events, I found the following Api call:
----
{
\"Role\": \"arn:aws:iam::********:role/test\",
\"MemorySize\": \"256\",
\"Runtime\": \"nodejs14.x\",
\"Description\": \"AWS Lambda Function that will create the website and upload it to the S3 bucket\\n\",
\"Timeout\": \"120\",
\"Handler\": \"index.handler\",
\"Code\": \"./website-creator\"
}
----

Inspecting the Stack template I can see the Lambda Function resource definition is referring to a local directory for the Code property

**Comment by ramprasadsv** [comment]
@Tarunjain19 you can deploy the solution in two ways, one by clicking the "Launch Stack" [button](https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/create/review?templateURL=https://aws-contact-center-blog.s3.amazonaws.com/ram/programmatically-search-for-users-using-an-api-in-amazon-connect/search-users.yaml&stackName=user-search-api) or you can clone the repo and following the instructions that is provided in the README.md file by executing the SAM commands.  Please let me know if that works for you.
