### ISSUE TITLE
Getting error in Cloudformation template of Module 3

### ISSUE THREAD

**Issue by rahjos4** [aws-samples/ac-multi-region-apis#3]
Hi Team,
We have followed below blog for AWS global resiliency implementation but getting error on importing Module 3 Cloudformation template.
https://aws.amazon.com/blogs/contact-center/build-a-multi-region-resilient-contact-center-with-amazon-connect-global-resiliency/ 

Error while importing Cloudformation template of Module 3 -
Properties_ validation failed for resource webSiteCreator with message: #/Code: expected type: JSONObject, found: String._

**Comment by emolvera** [comment]
I think the blog might be misleading, the CloudFormation stack should not be deployed via console because there are dependencies besides the YAML template. The correct way is to build it using SAM, as instructed in the [README.md](https://github.com/aws-samples/ac-multi-region-apis/blob/main/README.md):

> Use `sam` to build, invoke and deploy the function.
> 
> ##### SAM Build:
> Ensure you are in the root folder
> 
> `sam build --use-container`
> 
> ##### SAM Deploy:
> `sam deploy template.yaml --s3-bucket REPLACE_ME --stack-name REPLACE_ME --parameter-overrides ParameterKey=parS3BucketForWebSite,ParameterValue=REPLACE_ME --capabilities CAPABILITY_IAM`

**Comment by ramprasadsv** [comment]
@rahjos4 you can run the cloudformation template specified in the blog ONLY in us-west-2 region, however if you need to implement in a different region, then you have to clone the repo and follow the instructions provided in the [README.md](https://github.com/aws-samples/ac-multi-region-apis/blob/main/README.md) : 

> Use `sam` to build, invoke and deploy the function.
> 
> ##### SAM Build:
> Ensure you are in the root folder
> 
> `sam build --use-container`
> 
> ##### SAM Deploy:
> `sam deploy template.yaml --s3-bucket REPLACE_ME --stack-name REPLACE_ME --parameter-overrides ParameterKey=parS3BucketForWebSite,ParameterValue=REPLACE_ME --capabilities CAPABILITY_IAM`

**Comment by rahjos4** [comment]
@ramprasadsv @emolvera 
Tried to deploy using sam command & it's been executed but terminated with below error
"uploaded file must be a non empty zip"
please take a look on attached screenshots & suggest accordingly to proceed.
![2-Error_USWest-Oregon](https://user-images.githubusercontent.com/98079119/209163849-cb0532b5-2cfe-4a67-a271-289d427159f7.JPG)
![1-Sam_Deploy_USWest-Oregon1](https://user-images.githubusercontent.com/98079119/209163860-8cc06488-9994-4e63-b5a5-046c250ddafc.JPG)
