### ISSUE TITLE
This demo is failing when deploying with S3 error

### ISSUE THREAD

**Issue by BMassey73** [aws-samples/ac-multi-region-apis#4]
Hello, 

I tried this demo using the SAM deployment as well as the usual CloudFormation deployment and it seems to fail due to an issue with the S3 bucket ACL, which presumably is from the change AWS made to S3 in April regarding new S3 buckets.  Here is the failure message I receive from CloudFormation:  
"Invalid request provided: AWS::CloudFront::Distribution: The S3 bucket that you specified for CloudFront logs does not enable ACL access: bmassey215-06-15-2023-test-mrr-stack.s3.amazonaws.com (Service: CloudFront, Status Code: 400, Request ID: a9685ef3-f66e-4ea8-97af-8290408ca1bd)" (RequestToken: 1faf67f1-c4e6-c1c4-411b-5ccf166eab3d, HandlerErrorCode: InvalidRequest)"

I tried modifying the YAML file several different ways to get around this, such as changing the PublicAccessBlockConfiguration to all be False or adding an ObjectOwnership line in the properties under resources, etc, but none of them worked.  Is there a fix for this code/template file to account for the new S3 bucket creation ACL?  

Thank you

**Comment by ramprasadsv** [comment]
@BMassey73 I have fixed the issue with the template, please update your repo and try again.

**Comment by BMassey73** [comment]
Thank you, that worked!  Appreciate it!

**Comment by BMassey73** [comment]
Closing this issue
